<?php
$title = 'Delete album';
$url = $this->url('ffmpeg', 
[
    'action'    => 'deleteStream',
    'id'        => $id,
]);

$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete 
    "<?= $this->escapeHtml($stream->name) ?>"?
</p>

<form action="<?= $url ?>" method="post"> 
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $stream->id ?>" />
        <input type="submit" value="Yes" name="del" class="btn btn-danger" />
        <input type="submit" value="No" name="del" class="btn btn-success" />
    </div>
</form>