<?php 
$title =sprintf('Delete Stream Out "%s"', $streamOut->dst);
$url = $this->url('ffmpeg/streamout/deletestreamout', 
[
    'action'    => 'deletestreamout',
    'id'        => $id,
]);

$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete 
    "<?= $this->escapeHtml($title) ?>"
</p>

<form action="<?= $url ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?= (int) $streamOut->id ?>" />
    <input type="hidden" name="streamid" value="<?= (int) $streamOut->streamID ?>" />
    <input type="submit" value="Yes" name="del" class="btn btn-dnager" />
    <input type="submit" value="No" name="del" class="btn btn-success" />
</div>
</form>