<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF FFMPEG Encoder')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.theme.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.structure.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile('https://code.jquery.com/jquery-3.3.1.js')
        ->appendFile('https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')
        ->appendFile('https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js')
        ->appendFile($this->basePath('js/status.js'))
    ?>

</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('ffmpeg') ?>">
                    <img src="<?= $this->basePath('img/logo.jpg') ?>" height="28"
                        alt="Zend Framework <?= \FFMpeg\Module::VERSION ?>" />&nbsp;FFMpeg Encoder
                </a>
            </div>




            <div class="collapse navbar-collapse">
                <?php // update to: 
                ?>
                <?= $this->navigation('navigation')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setUlClass('nav navbar-nav') ?>
                <p id='sysinfo'></p>
            </div>

    </nav>
    <?php
    $flash = $this->flashMessenger();
    if ($flash->hasMessages()) {; ?>
    <?php
        //       echo $flash->render('info');
        $flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
    }
    ?>

    <div class="container fill">
        <?php ?>
        <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>

        <?= $this->content ?>


    </div>


</body>

</html>